// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Xcelerate.Data;

#nullable disable

namespace Xcelerate.Migrations
{
    [DbContext(typeof(XDbContext))]
    partial class XDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Xcelerate.Models.ExcelData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Field1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Field10")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Field2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Field3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Field4")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Field5")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Field6")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Field7")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Field8")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Field9")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("YourEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
